### PR TITLE
WIP Use NewClientWithIPAndWait when it creates metadataClient

### PR DESCRIPTION
**Pull request by niusmallnan**
Pls see https://github.com/rancher/rancher/issues/8603

### CODE REVIEW

**Comment by cjellick** [comment]
@niusmallnan please separate this into two commits: one for the vendor changes and one for the changes to our code

**Comment by niusmallnan** [comment]
@cjellick  have separate this into two commits.

**Comment by alena1108** [comment]
@niusmallnan is this PR still relevant? if so, could you rebase?

**Comment by niusmallnan** [comment]
@alena1108 
Still in the discussion, no final decision.
This PR has a lower priority for now.

**Comment by alena1108** [comment]
Closing as the pr is no longer relevant for rancher master (2.0)

**Pull request closed without merging**
