### PR TITLE
Make metadata address configurable and default to IP 169.254.169.250

### PR DESCRIPTION
**Pull request by superseb**
https://github.com/rancher/rancher/issues/11275

https://github.com/rancher/rancher/issues/9894

### CODE REVIEW

**Comment by alena1108** [comment]
@superseb can we make it configurable via catalog? METADATA_ADDRESS, similar to infra-templates/network-services/0/docker-compose.yml

**Comment by superseb** [comment]
@alena1108 As this is not a catalog item, where should I make it configurable?

**Comment by superseb** [comment]
This is updated to configurable address for ingress LB, tied to https://github.com/rancher/rancher-catalog/pull/1141

**Comment by alena1108** [comment]
LGTM

**Pull request merged**
