### PR TITLE
Default cert should be loaded first, so that haproxy uses the right cert as default.

### PR DESCRIPTION
**Pull request by prachidamle**
Specify the default cert first in the haproxy cfg file before all other certs. This makes haproxy present the right cert as default. Otherwise haproxy will present the first cert listed alphabetically from the cert directory (specified in haproxy's config file) as the default certificate.

Here is the haproxy documentation: https://cbonte.github.io/haproxy-dconv/1.6/configuration.html#5.1-crt

https://github.com/rancher/rancher/issues/8365

### CODE REVIEW

**Comment by prachidamle** [comment]
@alena1108 @cjellick please review

**Comment by cjellick** [comment]
I didn't look to closely at the tests, but it appears there is a framework for testing the configs. If thats what these tests are: https://github.com/rancher/lb-controller/blob/master/provider/haproxy/haproxy_test.go
can you please add a test for this change?

**Comment by prachidamle** [comment]
@cjellick test has been added to https://github.com/rancher/lb-controller/blob/master/provider/haproxy/haproxy_test.go

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
